In [32]:
import requests
import pandas as pd
import numpy as np

In [33]:
# Ler os dados
data_path = '../../data/lending_data.csv'
df = pd.read_csv(data_path)
df.head(2)

,ID,"""LIMIT_BAL""","""SEX""","""EDUCATION""","""MARRIAGE""","""AGE""","""PAY_0""","""PAY_2""","""PAY_3""","""PAY_4""",...,"""BILL_AMT4""","""BILL_AMT5""","""BILL_AMT6""","""PAY_AMT1""","""PAY_AMT2""","""PAY_AMT3""","""PAY_AMT4""","""PAY_AMT5""","""PAY_AMT6""","""default.payment.next.month"""
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1

In [34]:
df.columns = df.columns.str.strip().str.replace('"', '')

In [35]:
# vamos usar uma linha aleatória do dataframe apenas para ter um exemplo de input
input_df = df.sample(10)

In [36]:
input_df

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
27519,27520,460000.0,1,2,1,52,0,0,0,0,...,171579.0,163450.0,160547.0,8000.0,9000.0,8154.0,6000.0,6000.0,6000.0,0
14114,14115,50000.0,2,2,2,23,0,0,0,0,...,28553.0,30196.0,30208.0,2205.0,2204.0,1000.0,2013.0,5004.0,2009.0,0
18771,18772,20000.0,2,2,2,26,-1,-1,-1,-1,...,1119.0,-222.0,-222.0,376.0,987.0,1200.0,0.0,0.0,0.0,1
17171,17172,10000.0,2,2,2,27,1,2,0,0,...,6984.0,7120.0,7267.0,0.0,1257.0,1300.0,400.0,410.0,420.0,0
552,553,50000.0,1,1,1,56,0,0,0,0,...,28842.0,30399.0,29977.0,2500.0,1500.0,1100.0,2000.0,1500.0,1017.0,1
13941,13942,50000.0,1,3,1,49,0,0,0,-2,...,0.0,0.0,0.0,2400.0,0.0,0.0,0.0,0.0,0.0,1
8898,8899,50000.0,2,2,1,27,2,2,0,0,...,19522.0,19775.0,20325.0,0.0,1280.0,662.0,837.0,1000.0,1120.0,1
4472,4473,130000.0,1,3,3,52,0,0,0,0,...,45207.0,41556.0,42455.0,3003.0,2000.0,2000.0,2000.0,1590.0,2000.0,1
9064,9065,100000.0,2,2,2,32,0,0,0,0,...,58237.0,59643.0,63275.0,2700.0,2055.0,2500.0,2500.0,4800.0,2500.0,0
21223,21224,90000.0,1,2,2,34,0,0,2,0,...,12628.0,20172.0,73512.0,5700.0,0.0,2000.0,20172.0,73512.0,3000.0,0

In [37]:
# Retiramos o target (default.payment.next.month) dos dados, para termos o input que o nosso modelo está à espera 

input_data = input_df.drop("default.payment.next.month", axis=1)

# mlflow serve

O mlflow, através da funcionalidade de serving, permite facilmente expor numa API um modelo guardado no model registry.

Esta API aceita pedidos no endpoint `/invocations`

In [38]:
# devemos ir à UI do mlflow, À model registry, perceber qual é o input de dados esperado
records = input_data.to_dict(orient="records")

In [39]:
records

[{'ID': 27520,
  'LIMIT_BAL': 460000.0,
  'SEX': 1,
  'EDUCATION': 2,
  'MARRIAGE': 1,
  'AGE': 52,
  'PAY_0': 0,
  'PAY_2': 0,
  'PAY_3': 0,
  'PAY_4': 0,
  'PAY_5': 0,
  'PAY_6': 0,
  'BILL_AMT1': 177520.0,
  'BILL_AMT2': 174746.0,
  'BILL_AMT3': 168279.0,
  'BILL_AMT4': 171579.0,
  'BILL_AMT5': 163450.0,
  'BILL_AMT6': 160547.0,
  'PAY_AMT1': 8000.0,
  'PAY_AMT2': 9000.0,
  'PAY_AMT3': 8154.0,
  'PAY_AMT4': 6000.0,
  'PAY_AMT5': 6000.0,
  'PAY_AMT6': 6000.0},
 {'ID': 14115,
  'LIMIT_BAL': 50000.0,
  'SEX': 2,
  'EDUCATION': 2,
  'MARRIAGE': 2,
  'AGE': 23,
  'PAY_0': 0,
  'PAY_2': 0,
  'PAY_3': 0,
  'PAY_4': 0,
  'PAY_5': 0,
  'PAY_6': 0,
  'BILL_AMT1': 50105.0,
  'BILL_AMT2': 51099.0,
  'BILL_AMT3': 50269.0,
  'BILL_AMT4': 28553.0,
  'BILL_AMT5': 30196.0,
  'BILL_AMT6': 30208.0,
  'PAY_AMT1': 2205.0,
  'PAY_AMT2': 2204.0,
  'PAY_AMT3': 1000.0,
  'PAY_AMT4': 2013.0,
  'PAY_AMT5': 5004.0,
  'PAY_AMT6': 2009.0},
 {'ID': 18772,
  'LIMIT_BAL': 20000.0,
  'SEX': 2,
  'EDUCATION': 2,
  'MARRIAGE': 2,
  'AGE': 26,
  'PAY_0': -1,
  'PAY_2': -1,
  'PAY_3': -1,
  'PAY_4': -1,
  'PAY_5': -1,
  'PAY_6': -2,
  'BILL_AMT1': 767.0,
  'BILL_AMT2': 376.0,
  'BILL_AMT3': 987.0,
  'BILL_AMT4': 1119.0,
  'BILL_AMT5': -222.0,
  'BILL_AMT6': -222.0,
  'PAY_AMT1': 376.0,
  'PAY_AMT2': 987.0,
  'PAY_AMT3': 1200.0,
  'PAY_AMT4': 0.0,
  'PAY_AMT5': 0.0,
  'PAY_AMT6': 0.0},
 {'ID': 17172,
  'LIMIT_BAL': 10000.0,
  'SEX': 2,
  'EDUCATION': 2,
  'MARRIAGE': 2,
  'AGE': 27,
  'PAY_0': 1,
  'PAY_2': 2,
  'PAY_3': 0,
  'PAY_4': 0,
  'PAY_5': 0,
  'PAY_6': 0,
  'BILL_AMT1': 5150.0,
  'BILL_AMT2': 4922.0,
  'BILL_AMT3': 5941.0,
  'BILL_AMT4': 6984.0,
  'BILL_AMT5': 7120.0,
  'BILL_AMT6': 7267.0,
  'PAY_AMT1': 0.0,
  'PAY_AMT2': 1257.0,
  'PAY_AMT3': 1300.0,
  'PAY_AMT4': 400.0,
  'PAY_AMT5': 410.0,
  'PAY_AMT6': 420.0},
 {'ID': 553,
  'LIMIT_BAL': 50000.0,
  'SEX': 1,
  'EDUCATION': 1,
  'MARRIAGE': 1,
  'AGE': 56,
  'PAY_0': 0,
  'PAY_2': 0,
  'PAY_3': 0,
  'PAY_4': 0,
  'PAY_5': 0,
  'PAY_6': 0,
  'BILL_AMT1': 50715.0,
  'BILL_AMT2': 51073.0,
  'BILL_AMT3': 28185.0,
  'BILL_AMT4': 28842.0,
  'BILL_AMT5': 30399.0,
  'BILL_AMT6': 29977.0,
  'PAY_AMT1': 2500.0,
  'PAY_AMT2': 1500.0,
  'PAY_AMT3': 1100.0,
  'PAY_AMT4': 2000.0,
  'PAY_AMT5': 1500.0,
  'PAY_AMT6': 1017.0},
 {'ID': 13942,
  'LIMIT_BAL': 50000.0,
  'SEX': 1,
  'EDUCATION': 3,
  'MARRIAGE': 1,
  'AGE': 49,
  'PAY_0': 0,
  'PAY_2': 0,
  'PAY_3': 0,
  'PAY_4': -2,
  'PAY_5': -2,
  'PAY_6': -2,
  'BILL_AMT1': 50180.0,
  'BILL_AMT2': 51400.0,
  'BILL_AMT3': 0.0,
  'BILL_AMT4': 0.0,
  'BILL_AMT5': 0.0,
  'BILL_AMT6': 0.0,
  'PAY_AMT1': 2400.0,
  'PAY_AMT2': 0.0,
  'PAY_AMT3': 0.0,
  'PAY_AMT4': 0.0,
  'PAY_AMT5': 0.0,
  'PAY_AMT6': 0.0},
 {'ID': 8899,
  'LIMIT_BAL': 50000.0,
  'SEX': 2,
  'EDUCATION': 2,
  'MARRIAGE': 1,
  'AGE': 27,
  'PAY_0': 2,
  'PAY_2': 2,
  'PAY_3': 0,
  'PAY_4': 0,
  'PAY_5': 0,
  'PAY_6': 0,
  'BILL_AMT1': 49882.0,
  'BILL_AMT2': 44110.0,
  'BILL_AMT3': 44443.0,
  'BILL_AMT4': 19522.0,
  'BILL_AMT5': 19775.0,
  'BILL_AMT6': 20325.0,
  'PAY_AMT1': 0.0,
  'PAY_AMT2': 1280.0,
  'PAY_AMT3': 662.0,
  'PAY_AMT4': 837.0,
  'PAY_AMT5': 1000.0,
  'PAY_AMT6': 1120.0},
 {'ID': 4473,
  'LIMIT_BAL': 130000.0,
  'SEX': 1,
  'EDUCATION': 3,
  'MARRIAGE': 3,
  'AGE': 52,
  'PAY_0': 0,
  'PAY_2': 0,
  'PAY_3': 0,
  'PAY_4': 0,
  'PAY_5': 0,
  'PAY_6': 0,
  'BILL_AMT1': 106140.0,
  'BILL_AMT2': 69025.0,
  'BILL_AMT3': 58860.0,
  'BILL_AMT4': 45207.0,
  'BILL_AMT5': 41556.0,
  'BILL_AMT6': 42455.0,
  'PAY_AMT1': 3003.0,
  'PAY_AMT2': 2000.0,
  'PAY_AMT3': 2000.0,
  'PAY_AMT4': 2000.0,
  'PAY_AMT5': 1590.0,
  'PAY_AMT6': 2000.0},
 {'ID': 9065,
  'LIMIT_BAL': 100000.0,
  'SEX': 2,
  'EDUCATION': 2,
  'MARRIAGE': 2,
  'AGE': 32,
  'PAY_0': 0,
  'PAY_2': 0,
  'PAY_3': 0,
  'PAY_4': 0,
  'PAY_5': 0,
  'PAY_6': 0,
  'BILL_AMT1': 54933.0,
  'BILL_AMT2': 56151.0,
  'BILL_AMT3': 56677.0,
  'BILL_AMT4': 58237.0,
  'BILL_AMT5': 59643.0,
  'BILL_AMT6': 63275.0,
  'PAY_AMT1': 2700.0,
  'PAY_AMT2': 2055.0,
  'PAY_AMT3': 2500.0,
  'PAY_AMT4': 2500.0,
  'PAY_AMT5': 4800.0,
  'PAY_AMT6': 2500.0},
 {'ID': 21224,
  'LIMIT_BAL': 90000.0,
  'SEX': 1,
  'EDUCATION': 2,
  'MARRIAGE': 2,
  'AGE': 34,
  'PAY_0': 0,
  'PAY_2': 0,
  'PAY_3': 2,
  'PAY_4': 0,
  'PAY_5': -1,
  'PAY_6': -1,
  'BILL_AMT1': 77846.0,
  'BILL_AMT2': 50281.0,
  'BILL_AMT3': 14033.0,
  'BILL_AMT4': 12628.0,
  'BILL_AMT5': 20172.0,
  'BILL_AMT6': 73512.0,
  'PAY_AMT1': 5700.0,
  'PAY_AMT2': 0.0,
  'PAY_AMT3': 2000.0,
  'PAY_AMT4': 20172.0,
  'PAY_AMT5': 73512.0,
  'PAY_AMT6': 3000.0}]

In [ ]:
#response = requests.post("http://127.0.0.1:5001/invocations", json={"dataframe_records": records})
#response.json()
#mlflow_url = "http://127.0.0.1:5001/invocations"
#response = requests.post(mlflow_url, json={"dataframe_records": records})
mlflow_url = "http://127.0.0.1:5001/invocations"
response = requests.post(mlflow_url, json={"dataframe_records": records})

In [ ]:

response = requests.post("http://127.0.0.1:5001/invocations", json={"dataframe_records": [{
  'LIMIT_BAL': 50000,
    'SEX': 2,
    'EDUCATION': 1,
    'MARRIAGE': 2,
    'AGE': 35,
    'PAY_0': 0,
    'PAY_2': 0,
    'PAY_3': 0,
    'PAY_4': 0,
    'PAY_5': 0,
    'PAY_6': 0,
    'BILL_AMT1': 0,
    'BILL_AMT2': 0,
    'BILL_AMT3': 0,
    'BILL_AMT4': 0,
    'BILL_AMT5': 0,
    'BILL_AMT6': 0,
    'PAY_AMT1': 0,
    'PAY_AMT2': 0,
    'PAY_AMT3': 0,
    'PAY_AMT4': 0,
    'PAY_AMT5': 0,
    'PAY_AMT6': 0}]})
response.json()

# FastAPI

In [ ]:
# devemos ir aos docs da fastapi: http://127.0.0.1:5002/docs para perceber o input esperado
#request_dict = records[0]

In [ ]:
#request_dict

In [ ]:
# fazer pedido à app com os inputs
#fastapi_url = "http://127.0.0.1:5002/predict"
#response = requests.post("http://127.0.0.1:5003/predict", json=request_dict)
fastapi_url = "http://127.0.0.1:5003/predict"
request_dict = records[0]
response = requests.post(fastapi_url, json=request_dict)

In [ ]:
# recebemos uma resposta com a previsão
response.json()